### ISSUE TITLE
node-red crashes when using messageID function

### ISSUE THREAD

**Issue by ggreeve** [Vruizvil/node-red-contrib-iota-chrysalis#3]
node-red crashes when using messageID function with invalid argument.
clear argument and inject random string, then node-red crashes.

**Comment by vanvuongngo** [comment]
Related to this pullrequest?: https://github.com/Vruizvil/node-red-contrib-iota-chrysalis/pull/5

**Comment by Vruizvil** [comment]
Better error handle in release 1.4.0

**Comment by Vruizvil** [comment]
Better error handle in release 1.4.0
